### ISSUE TITLE
UnicodeEncodeError: 'gbk' codec can't encode character '\xa0' in position 72729: illegal multibyte  sequence

### ISSUE THREAD

**Issue by huyinjie** [selfshore/spiders#4]
点评的代码在填入用户名密码后报错，尝试修改为UTF-8编码依然报错

```python
with open('temp.js', 'r', encoding='utf-8')as f:
        content = f.read()
```

**Comment by selfshore** [comment]
> 点评的代码在填入用户名密码后报错，尝试修改为UTF-8编码依然报错
> 
> ```python
> with open('temp.js', 'r', encoding='utf-8')as f:
>         content = f.read()
> ```

这是哪个文件下的代码

**Comment by selfshore** [comment]
> > ```
> 
> 这是哪个文件下的代码

**Comment by huyinjie** [comment]
你好 是 https://github.com/selfshore/spiders/blob/master/大众点评登录/run.py 下的代码，后来将 https://github.com/selfshore/spiders/blob/master/大众点评登录/temp.js 文件重新下载覆盖能成功运行。
请问下这个程序是不是不能获取到这三个Cookie值 _lxsdk_cuid/ _lxsdk /_hc.v

**Comment by selfshore** [comment]
> 你好是[https://github.com/selfshore/spiders/blob/master/大众点评登录/run.py](https://github.com/selfshore/spiders/blob/master/%E5%A4%A7%E4%BC%97%E7%82%B9%E8%AF%84%E7%99%BB%E5%BD%95/run.py)下的代码，后来将[https://github.com/selfshore/spiders/blob/master/大众点评登录/temp.js](https://github.com/selfshore/spiders/blob/master/%E5%A4%A7%E4%BC%97%E7%82%B9%E8%AF%84%E7%99%BB%E5%BD%95/temp.js)文件重新下载覆盖能成功运行。
> 请问下这个程序是不是不能获取到这三个曲奇值_lxsdk_cuid / _lxsdk /_hc.v

看run.py注释的那两行，有两个cookie可能是你需要的

**Comment by huyinjie** [comment]
可以使用 不过生成的uuid和浏览器里的不一样 应该是计算方法包含了浏览器特征 感谢
